import type { Metadata } from "next"
import { Jua, Inter } from "next/font/google"
import "./globals.scss"
import { PedidoProvider } from "@/shared/store/PedidoContext"
import { Toaster } from "react-hot-toast"

const jua = Jua({
	variable: "--font-geist-mono",
	subsets: ["latin"],
	weight: ["400"],
})

const inter = Inter({
	variable: "--font-geist-mono",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
	title: "El Rey Costijhon",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${jua.variable} ${inter.variable}`}>
				<PedidoProvider>{children}</PedidoProvider>
				<Toaster
					position="bottom-center"
					toastOptions={{
						style: {
							fontFamily: "Inter, sans-serif",
							fontSize: "14px",
							padding: "16px 24px",
							marginBottom: "80px", // esto afecta entre toasts
						},
						success: {
							iconTheme: {
								primary: "#4ade80", // verde
								secondary: "#ecfdf5",
							},
						},
					}}
				/>
			</body>
		</html>
	)
}
